name: Automatic image build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false # Don't fail all if any of the jobs is failing
      matrix:
        TARGET: [pi-buster, jetson-nano-2gb-bionic]

    steps:
    - uses: actions/checkout@v2
    - name: dep
      run: sudo apt-get install unzip curl git qemu qemu-user-static binfmt-support
    - name: configure
      run: sudo ./build.sh ${{ matrix.TARGET }} testing
