name: Automatic image build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false # Don't fail all if any of the jobs is failing
      matrix:
        TARGET: [pi-buster, jetson-nano-2gb-bionic] # <-- Add targets here!

    steps:
    - name: Setup env
      run: |
        echo "DT=$(date +'%Y-%m-%d_%H%M')" >> $GITHUB_ENV
        echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV
    
    
    ### ONLY THIS RELEVANT FOR BUILDING ###
    - uses: actions/checkout@v2
    - name: dep
      run: sudo apt-get install unzip curl git qemu qemu-user-static binfmt-support
    - name: configure
      run: sudo ./build.sh ${{ matrix.TARGET }} testing
    ########################################


    - name: Compose release filename
      # https://stackoverflow.com/questions/58033366/how-to-get-current-branch-within-github-actions
      run: echo "artifact_name=OpenHD-image-${{ matrix.TARGET }}-${{ matrix.DISTRO }}-${GITHUB_REF##*/}-${{ env.DT }}" >> $GITHUB_ENV
        
    - name: Pack ${{ env.artifact_name }}
      uses: 'actions/upload-artifact@v2'
      with:
        name: "${{ env.artifact_name }}"
        path: |
          ./deploy/*.img
          if-no-files-found: error
