name: Image build on event

on:
  push:
    branches: [ master, "2.0", "2.1-milestones","sizestest" ]
  pull_request:
    branches: [ master, "2.0" ]
  workflow_dispatch:
#  schedule:
#    - cron: '0 2 * * *' # run at 2 AM UTC

jobs:
  build:

    runs-on: ubuntu-20.04
    
    strategy:
      fail-fast: false # Don't fail all if any of the jobs is failing
      matrix:
        TESTING: [evo]
        TARGET: [pi-legacy, pi-bullseye, jetson-nano-2gb-bionic, jetson-nano-4gb-bionic] # <-- Add targets here!

    steps:
    - name: Maximize build space
      uses: easimon/maximize-build-space@master
      with:
        root-reserve-mb: 512
        swap-size-mb: 1024
        remove-dotnet: 'true'
        remove-android: 'true'
        remove-haskell: 'true'
        overprovision-lvm: 'true'
    - name: Setup env
      run: |
        sudo rm -Rf /usr/share/doc
        sudo rm -Rf /home/linuxbrew
        sudo rm -Rf /home/runner-admin
        sudo rm -Rf /opt/hostedtoolcache
        sudo rm -Rf /opt/microsoft
        sudo rm -Rf /opt/hhvm
        sudo apt remove -y php8.1-cgi fonts-noto-color-emoji aspnetcore-targeting-pack-3.1 aspnetcore-targeting-pack-6.0 fonts-lato python3-twisted aspnetcore-targeting-pack-5.0
        sudo apt remove -y dotnet* temurin-17-jdk temurin-11-jdk adoptopenjdk-11-hotspot libgl1-mesa-dri google-cloud-sdk hhvm google-chrome-stable firefox mongodb-mongosh qemu-user-static temurin-8-jdk adoptopenjdk-8-hotspot llvm-10-dev powershell snapd mysql-server-core-8.0 moby-containerd mono-devel mongodb-org-server
        sudo apt remove -y libgcc-9-dev libc6-i386 liblldb-10 libasan5 moby-runc mono-roslyn liblldb-11 liblldb-12 libruby2.7 perl-modules-5.30 libwxgtk3.0-gtk3-0v5 aspnetcore-runtime-3.1 libstdc++-9-dev libstdc++-10-dev aspnetcore-runtime-5.0 
        sudo apt remove -y sphinxsearch libc6-dev iso-codes libpython3.8-dev netstandard-targeting-pack-2.1 aspnetcore-runtime-6.0 humanity-icon-theme monodoc-manual libz3-4 ruby2.7-doc mono-utils linux-headers-5.13.0-1031-azure
        sudo apt autoremove -y
        echo "DT=$(date +'%Y-%m-%d_%H%M')" >> $GITHUB_ENV
        echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV
    
    
    ### ONLY THIS RELEVANT FOR BUILDING ###
    - uses: actions/checkout@v2
    - name: update
      run: sudo apt-get update
    - name: dep
      run: sudo apt-get install unzip curl git qemu qemu-user-static binfmt-support
    - name: configure
      run: sudo ./build.sh ${{ matrix.TARGET }} ${{ matrix.TESTING }} small
    - name: remove old image to make space
      run: |
        sudo rm -Rf -v ./work-jetson-nano-2gb-bionic/03-Preconfiguration/*
        sudo rm -Rf -v ./work-jetson-nano-4gb-bionic/03-Preconfiguration/*
        sudo rm -Rf -v ./work-pi-bullseye/03-Preconfiguration/*
        sudo rm -Rf -v ./work-pi-legacy-bullseye/03-Preconfiguration/*
    - name: magic
      run: |
        ls -a
        sudo df -h
        sudo mv ./deploy/*.img ./OpenHD-image-${{ matrix.TARGET }}-${{ matrix.TESTING }}-${{ matrix.DISTRO }}-${GITHUB_REF##*/}-${{ env.DT }}.img
        echo "moved image"
        sudo rm -rvf deploy*
        sudo rm -rvf work*
        sudo rm -Rf /usr/share/doc
        sudo rm -Rf /home/linuxbrew
        sudo rm -Rf /home/runner-admin
        sudo rm -Rf /opt/hostedtoolcache
        sudo rm -Rf /opt/microsoft
        sudo rm -Rf /opt/hhvm
        sudo apt autoremove -y
        sudo df -h
        
    ########################################


    - name: Compose release filename
      # https://stackoverflow.com/questions/58033366/how-to-get-current-branch-within-github-actions
      run: echo "artifact_name=OpenHD-image-${{ matrix.TARGET }}-${{ matrix.TESTING }}-${{ matrix.DISTRO }}-${GITHUB_REF##*/}-${{ env.DT }}" >> $GITHUB_ENV
        
    - name: Pack image for ${{ matrix.TARGET }} ${{ matrix.TESTING }}
      uses: 'actions/upload-artifact@v2'
      with:
        name: "${{ env.artifact_name }}"
        path: |
          *.img
          if-no-files-found: error
