name: Image build on event

on:
  push:
    branches: [ "2.3-evo" ]
  pull_request:
    branches: [ "2.3-evo" ]
  workflow_dispatch:
#  schedule:
#    - cron: '0 2 * * *' # run at 2 AM UTC

jobs:
  build:

    runs-on: ubuntu-22.04
    
    strategy:
      fail-fast: false # Don't fail all if any of the jobs is failing

    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - uses: pguyot/arm-runner-action@v2.5.2
      id: build_image
      with:
        base_image: https://openhdfpv.org/wp-content/Downloader/OpenHD-image-pi-bullseye-configurable-release--2.3-evo-2023-02-04_0212.img.xz
        image_additional_mb: 4000
        copy_repository_path: /opt
        copy_artifact_path: OpenHD
        import_github_env: true
        commands: |
    - name: Generate Update file
      run: |
        bash additionalFiles/updateOpenHD.sh


    - name: Pack image for ${{ matrix.TARGET }}
      uses: 'actions/upload-artifact@v2'
      with:
        name: "${{ env.artifact_name }}"
        path: |
          *.zip
          if-no-files-found: error
