name: Test S3 upload with custom endpoint

on:
  workflow_dispatch:

jobs:
  upload-file:
    runs-on: ubuntu-latest
    steps:
    - name: Generate random hash
      run: |
        echo "random_hash=$(openssl rand -hex 4)" >> $GITHUB_ENV
        echo "Random hash: $random_hash"
    - name: Create empty file
      run: |
        touch ${{ env.random_hash }}.txt     
    
    - name: copy file to s3
      shell: bash
      env:
        aws_key_id: ${{ secrets.DATA_ACCESS}}
        aws_secret_access_key: ${{ secrets.DATA_KEY }}
        aws_s3_bucket: ${{ secrets.S3_BUCKET }}
      run: |
        aws configure set aws_access_key_id $aws_key_id
        aws configure set aws_secret_access_key $aws_secret_access_key 
        #aws configure set default.region us-east-1
        aws s3 --endpoint-url https://data.openhdfpv.org cp ${{ env.random_hash }}.txt s3://test
  
  
