name: Test S3 upload with custom endpoint

on:
  workflow_dispatch:

jobs:
  upload-file:
    runs-on: ubuntu-latest
    steps:
    - name: Generate random hash
      run: |
        echo "random_hash=$(openssl rand -hex 4)" >> $GITHUB_ENV
        echo "Random hash: $random_hash"
    - name: Create empty file
      run: |
        touch ${{ env.random_hash }}.txt     
    
    - name: copy file to s3
      shell: bash
      env:
        aws_key_id: ${{ secrets.DIGITALOCEAN_ACCESS_KEY_ID}}
        aws_secret_access_key: ${{ secrets.DIGITALOCEAN_SECRET_ACCESS_KEY }}
        aws_s3_bucket: ${{ secrets.S3_BUCKET }}
        AWS_EC2_METADATA_DISABLED: true
      run: |
        aws configure set aws_access_key_id $aws_key_id
        aws configure set aws_secret_access_key $aws_secret_access_key 
        aws s3 --endpoint-url https://fra1.digitaloceanspaces.com cp ${{ env.random_hash }}.txt s3://openhd-test
  
  
