name: Image Release Jetson-4GB

on:
  push:
    paths:
      - 'last.release'

#  schedule:
#    - cron: '0 2 * * *' # run at 2 AM UTC

jobs:
  build:
    runs-on: ubuntu-22.04
    
    strategy:
      fail-fast: false # Don't fail all if any of the jobs is failing
      matrix:
        TESTING: [testing]
        TARGET: [jetson-nano-4gb-bionic] # <-- Add targets here!

    steps:
    - name: Maximize build space
      uses: easimon/maximize-build-space@master
      with:
        root-reserve-mb: 512
        swap-size-mb: 1024
        remove-dotnet: 'true'
        remove-android: 'true'
        remove-haskell: 'true'
        overprovision-lvm: 'true'
    - name: Setup env
      run: |

        echo "DT=$(date +'%Y-%m-%d_%H%M')" >> $GITHUB_ENV
        echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV
    
    
    ### ONLY THIS RELEVANT FOR BUILDING ###
    - uses: actions/checkout@v3
    - name: update
      run: sudo apt-get update
    - name: upgrade
      run: sudo apt-get upgrade -y
    - name: dep
      run: sudo apt-get install -y unzip curl git qemu qemu-user-static binfmt-support
    - name: Build Image
      run: | 
         sudo ./build.sh ${{ matrix.TARGET }} ${{ matrix.TESTING }}
# - name: FAKE IMAGE FOR DEBUG
#   run: | 
#     mkdir -p ./deploy/
#     cd ./deploy/
#     touch OpenHD-image-pi-bullseye-testing--2.2.3-evo-2022-11-26_1622.img
#     echo "test" > OpenHD-image-pi-bullseye-testing--2.2.3-evo-2022-11-26_1622.img
#     mv OpenHD* ../
    - name: remove old image to make space
      run: |
        sudo rm -Rf -v ./work-jetson-nano-2gb-bionic/03-Preconfiguration/*
        sudo rm -Rf -v ./work-jetson-nano-4gb-bionic/03-Preconfiguration/*
        sudo rm -Rf -v ./work-pi-bullseye/03-Preconfiguration/*
        sudo rm -Rf -v ./work-pi-legacy-bullseye/03-Preconfiguration/*
    - name: magic
      run: |
        ls -a
        sudo df -h
        sudo mv ./deploy/*.img ./OpenHD-image-${{ matrix.TARGET }}-${{ matrix.TESTING }}-${{ matrix.DISTRO }}-${GITHUB_REF##*/}-${{ env.DT }}.img
        echo "moved image"
        sudo rm -rvf deploy*
        sudo rm -rvf work*
        sudo rm -Rf /usr/share/doc
        sudo rm -Rf /home/linuxbrew
        sudo rm -Rf /home/runner-admin
        sudo rm -Rf /opt/hostedtoolcache
        sudo rm -Rf /opt/microsoft
        sudo rm -Rf /opt/hhvm
        sudo apt autoremove -y
        sudo df -h
        
    ########################################


    - name: Compose release filename
      # https://stackoverflow.com/questions/58033366/how-to-get-current-branch-within-github-actions
      run: echo "artifact_name=OpenHD-image-release-${{ matrix.TARGET }}-${{ matrix.TESTING }}-${{ matrix.DISTRO }}-${GITHUB_REF##*/}-${{ env.DT }}" >> $GITHUB_ENV
        
    - name: Pack image for ${{ matrix.TARGET }} ${{ matrix.TESTING }}
      uses: 'actions/upload-artifact@v2'
      with:
        name: "${{ env.artifact_name }}"
        path: |
          *.img
          if-no-files-found: error

  upload:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/download-artifact@v3
      with:
        name: "${{ env.artifact_name }}"
    
    - name: compress
      run: |
        ls -a
        cd OpenHD*
        sha256sum * | cut -f 1 -d " " > ../sha256
        echo 'NAME<<EOF' >> $GITHUB_ENV
        ls -1 | sed -e 's/.img/.img.gz/g' >> $GITHUB_ENV
        echo 'EOF' >> $GITHUB_ENV
        echo 'SIZEFULL<<EOF' >> $GITHUB_ENV
        wc -c *.img | cut -f 1 -d " " >> $GITHUB_ENV
        echo 'EOF' >> $GITHUB_ENV
        gzip -v *.img
        ls -a
        mv * ../
        ls -a
        sleep 15m
    - name: debug
      run: |
        echo "${{ env.NAME }}"    
        
    - name: Upload file via SSH
      uses: nicklasfrahm/scp-action@main
      with:
        direction: upload
        host: ${{ secrets.LINK }}
        port: ${{ secrets.PORT }}
        username: ${{ secrets.USER }}
        insecure_password: ${{ secrets.PASSWORD }}
        insecure_ignore_fingerprint: true
        source: ${{ env.NAME }}
        target: ${{ env.NAME }}

    - name: Download yaml file via SSH
      uses: nicklasfrahm/scp-action@main
      with:
        direction: download
        host: ${{ secrets.LINK }}
        port: ${{ secrets.PORT }}
        username: ${{ secrets.USER }}
        insecure_password: ${{ secrets.PASSWORD }}
        insecure_ignore_fingerprint: true
        source: os_list_imagingutility_v3_j2g.json
        target: os_list_imagingutility_v3_j4g.json

    - name: update YAMLFILE for the ImageWriter
      run: |
        ls -a      
        export NAME=$(cat last.release)
        export FILESIZE=${{ env.SIZEFULL }}
        export FILENAME=${{ env.NAME }}
        export DOWNLOADSIZE=$(wc -c *.gz | cut -f 1 -d " ")
        export SUM=$(cat sha256)
        export RELEASEDATE=$(date +%Y-%m-%d)

        sed -i "s/RELEASENAME/$NAME/ig" os_list_imagingutility_v3_j4g.jso
        sed -i "s/FILENAME/$FILENAME/ig" os_list_imagingutility_v3_j4g.jso       
        sed -i "s/FILESIZE/$FILESIZE/ig" os_list_imagingutility_v3_j4g.jso       
        sed -i "s/SHASUM/$SUM/ig" os_list_imagingutility_v3_j4g.jso       
        sed -i "s/DOWNLOADSIZE/$DOWNLOADSIZE/ig" os_list_imagingutility_v3_j4g.jso        
        sed -i "s/RELEASEDATE/$RELEASEDATE/ig" os_list_imagingutility_v3_j4g.jso            

    - name: Upload YAMLFILE
      uses: nicklasfrahm/scp-action@main
      with:
        direction: upload
        host: ${{ secrets.LINK }}
        port: ${{ secrets.PORT }}
        username: ${{ secrets.USER }}
        insecure_password: ${{ secrets.PASSWORD }}
        insecure_ignore_fingerprint: true
        source: os_list_imagingutility_v3_j4g.jso
        target: os_list_imagingutility_v3.jso